import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Max Mallett | Frontend Developer',
    description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body
            className={inter.className + ' text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900"'}
        >{children}</body>
    </html>
  )
}